### PR TITLE
Improved Italian translation of backup

### PR DESCRIPTION
**Pull request by Vladi69**
I propose a better Italian translation (IMHO) of last strings added to app

### CODE REVIEW

**Comment by Vladi69** [comment]
> https://github.com/AndreyPavlenko/Fermata/blob/7c991e8a6efa91b78fa7531b70081c578644ca6d/fermata/src/main/res/values-it/strings.xml#L279
> 
> This line should be plural, other things are okay for me too. "Importa preferenze" instead of "Importa preferenza"

Yep!

**Comment by Vladi69** [comment]
Added a new commit with the correction

**Comment by Vladi69** [comment]
I like new logo, really not bad!
Great job

**Comment by AndreyPavlenko** [comment]
Thanks!

**Pull request merged**
